#!/usr/bin/env bash

git clone https://github.com/neovim/neovim $HOME/tmp/neovim 
cd $HOME/tmp/neovim
git fetch
git checkout stable

sudo apt-get install ninja-build gettext cmake curl build-essential git
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
